"""initial tables

Revision ID: d003bdeaaa34
Revises: 
Create Date: 2025-11-29 12:09:13.097586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd003bdeaaa34'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('movieId', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('genres', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('movieId')
    )
    op.create_index(op.f('ix_movies_movieId'), 'movies', ['movieId'], unique=False)
    op.create_table('links',
    sa.Column('movieId', sa.Integer(), nullable=False),
    sa.Column('imdbId', sa.Integer(), nullable=True),
    sa.Column('tmdbId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movieId'], ['movies.movieId'], ),
    sa.PrimaryKeyConstraint('movieId')
    )
    op.create_table('ratings',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('movieId', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['movieId'], ['movies.movieId'], ),
    sa.PrimaryKeyConstraint('userId', 'movieId')
    )
    op.create_table('tags',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('movieId', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['movieId'], ['movies.movieId'], ),
    sa.PrimaryKeyConstraint('userId', 'movieId', 'tag', 'timestamp')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.drop_table('ratings')
    op.drop_table('links')
    op.drop_index(op.f('ix_movies_movieId'), table_name='movies')
    op.drop_table('movies')
    # ### end Alembic commands ###
